- hosts: demoserver
  roles:
    - { role: postgresql, tags: ["postgresql"] }
    - { role: supervisor, tags: ["supervisor"] }
    - { role: injector, tags: ["injector"] }
    - { role: webserver, tags: ["webserver"] }
