---

- name: add injector service to supervisor
  template:
    src: injector.conf.j2
    dest: "/etc/supervisor.d/injector.conf"
    owner: root
    group: root 
  become: yes

- name: update supervisor if necessary
  shell: "supervisorctl update"
  become: yes
