---

- name: create injector dirs
  become: yes
  file:
    path: "{{ item }}"
    owner: "{{ injector_user }}"
    group: "{{ injector_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ work_dir }}"
    - "{{ log_dir }}"
    - "{{ datasource_dir }}"

- name: create injector virtualenv
  become: yes
  become_user: "{{ injector_user }}"
  pip:
    name: "{{ item }}"
    virtualenv: "{{ work_dir }}/venv"
  with_items:
    - psycopg2
    - futures
    - tabulate
