---

- name: install webserver.py
  template: 
    src: webserver.py.j2
    dest: "{{ webserver_path }}/injector.py"
    owner: "{{ webserver_user }}"
    group: "{{ webserver_group }}"
    mode: 0755

- name: install pgpass
  become: true
  template: 
    src: pgpass.j2
    dest: "/root/.pgpass"
    owner: "root"
    group: "root"
    mode: 0600
